---

- name: Link gtk folders
  file:
    src: "{{ files_path }}gtk/{{ item }}"
    dest: "{{ user_path }}.config/{{ item }}"
    state: link
    force: yes
  with_items:
      - gtk-2.0
      - gtk-3.0
      - gtkrc
      - gtkrc-2.0